import {
  GridIcon,
  Folder01Icon,
  FolderCloudIcon,
  Calendar01Icon,
  UserMultiple02Icon,
  DatabaseIcon,
  Wifi01Icon,
  Notification02Icon,
  ArrowMoveDownRightIcon,
  ListViewIcon,
  PowerServiceIcon,
  Settings01Icon,
  ArrowLeft01Icon,
  Logout01Icon,
  Search01Icon,
} from "hugeicons-react";

export const iconMap = {
  overview: GridIcon,
  files: Folder01Icon,
  backups: FolderCloudIcon,
  schedules: Calendar01Icon,
  users: UserMultiple02Icon,
  databases: DatabaseIcon,
  network: Wifi01Icon,
  webhooks: Notification02Icon,
  split: ArrowMoveDownRightIcon,
  activity: ListViewIcon,
  startup: PowerServiceIcon,
  settings: Settings01Icon,
  back: ArrowLeft01Icon,
  logout: Logout01Icon,
  search: Search01Icon,
};
