// WebSocket constants and configuration
export const WEBSOCKET_CONSTANTS = {
  MAX_HISTORY_LENGTH: 60,
  MAX_CONSOLE_LINES: 500,
  MAX_RECONNECT_ATTEMPTS: 5,
  RECONNECT_BASE_DELAY: 1000,
  RECONNECT_MAX_DELAY: 30000,
};
