import {
  createCipheriv,
  createDecipheriv,
  createHash,
  randomBytes,
} from "node:crypto"

/**
 * AES-256-GCM symmetric encryption for at-rest secrets the API needs to
 * recover (database root passwords, generated DB user passwords). The
 * encryption key is derived from `BETTER_AUTH_SECRET` via SHA-256 so we
 * don't add yet another env var; if the better-auth secret rotates,
 * encrypted blobs become unreadable, which is acceptable because this
 * data can be regenerated by recreating database hosts.
 *
 * Format on disk: base64( iv || ciphertext || authTag ) where iv is 12
 * bytes and authTag is 16 bytes.
 */
const deriveKey = (secret: string): Buffer =>
  createHash("sha256").update(secret).digest()

export const encryptSecret = (plaintext: string, secret: string): string => {
  const key = deriveKey(secret)
  const iv = randomBytes(12)
  const cipher = createCipheriv("aes-256-gcm", key, iv)
  const ct = Buffer.concat([cipher.update(plaintext, "utf8"), cipher.final()])
  const tag = cipher.getAuthTag()
  return Buffer.concat([iv, ct, tag]).toString("base64")
}

export const decryptSecret = (blob: string, secret: string): string => {
  const buf = Buffer.from(blob, "base64")
  if (buf.length < 12 + 16) throw new Error("crypto: blob too short")
  const iv = buf.subarray(0, 12)
  const tag = buf.subarray(buf.length - 16)
  const ct = buf.subarray(12, buf.length - 16)
  const key = deriveKey(secret)
  const decipher = createDecipheriv("aes-256-gcm", key, iv)
  decipher.setAuthTag(tag)
  return Buffer.concat([decipher.update(ct), decipher.final()]).toString("utf8")
}

/**
 * Generate a URL-safe random password. Defaults to 24 characters of
 * unambiguous alphanumeric (no l/I, no 0/O) — long enough to resist
 * brute force, short enough to copy-paste, safe to drop into a
 * connection string without escaping.
 */
export const generatePassword = (length = 24): string => {
  const alphabet =
    "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789"
  const buf = randomBytes(length)
  let out = ""
  for (let i = 0; i < length; i += 1) {
    const byte = buf[i]
    if (byte === undefined) continue
    out += alphabet[byte % alphabet.length]
  }
  return out
}
