import { Command, CommandContext } from "./types";
import {
  Server,
  Settings,
  Users,
  BarChart3,
  Shield,
  Inbox,
  Home,
  Database,
  Clock,
  Network,
  Lock,
  BookOpen,
} from "lucide-react";

/**
 * Navigation commands for the command palette
 * Includes main navigation, server pages, and admin sections
 */
export const navigationCommands: Command[] = [
  // Main Navigation
  {
    id: "nav-servers",
    label: "Go to Servers",
    description: "View all your servers",
    icon: <Server className="size-4" />,
    category: "navigation",
    type: "simple",
    shortcut: ["g", "s"],
    isAvailable: () => true,
    action: { navigate: "/servers" },
    keywords: ["servers", "list", "overview"],
    priority: 100,
  },
  {
    id: "nav-account",
    label: "Go to Account",
    description: "View your account settings",
    icon: <Settings className="size-4" />,
    category: "navigation",
    type: "simple",
    shortcut: ["g", "a"],
    isAvailable: () => true,
    action: { navigate: "/account" },
    keywords: ["account", "profile", "settings"],
    priority: 99,
  },
  {
    id: "nav-admin",
    label: "Go to Admin Panel",
    description: "Access admin controls",
    icon: <Shield className="size-4" />,
    category: "navigation",
    type: "simple",
    shortcut: ["g", "x"],
    isAvailable: (ctx: CommandContext) => ctx.isAdmin,
    action: { navigate: "/admin" },
    keywords: ["admin", "panel"],
    priority: 98,
  },

  // Account Submenu
  {
    id: "nav-account-settings",
    label: "Account Settings",
    description: "Manage your account",
    icon: <Settings className="size-4" />,
    category: "navigation",
    type: "simple",
    isAvailable: () => true,
    action: { navigate: "/account" },
    keywords: ["account", "settings", "profile"],
    priority: 50,
  },
  {
    id: "nav-notifications",
    label: "Notifications",
    description: "View your notifications",
    icon: <Inbox className="size-4" />,
    category: "navigation",
    type: "simple",
    isAvailable: () => true,
    action: { navigate: "/account/notifications" },
    keywords: ["notifications", "inbox"],
    priority: 49,
  },

  // Server Navigation (when on server page)
  {
    id: "nav-server-overview",
    label: "Server Overview",
    description: "View server overview",
    icon: <Home className="size-4" />,
    category: "navigation",
    type: "simple",
    isAvailable: (ctx: CommandContext) => !!ctx.serverId,
    action: {
      navigate: (ctx: CommandContext) => `/servers/${ctx.serverId}/overview`,
    },
    keywords: ["overview", "dashboard"],
    priority: 40,
  },
  {
    id: "nav-server-files",
    label: "File Manager",
    description: "Browse and manage files",
    icon: <Database className="size-4" />,
    category: "navigation",
    type: "simple",
    isAvailable: (ctx: CommandContext) => !!ctx.serverId,
    action: {
      navigate: (ctx: CommandContext) => `/servers/${ctx.serverId}/files`,
    },
    keywords: ["files", "manager", "browse"],
    priority: 39,
  },
  {
    id: "nav-server-backups",
    label: "Backups",
    description: "View and manage backups",
    icon: <Lock className="size-4" />,
    category: "navigation",
    type: "simple",
    isAvailable: (ctx: CommandContext) => !!ctx.serverId,
    action: {
      navigate: (ctx: CommandContext) => `/servers/${ctx.serverId}/backups`,
    },
    keywords: ["backups", "restore"],
    priority: 38,
  },
  {
    id: "nav-server-schedules",
    label: "Schedules",
    description: "Manage server schedules",
    icon: <Clock className="size-4" />,
    category: "navigation",
    type: "simple",
    isAvailable: (ctx: CommandContext) => !!ctx.serverId,
    action: {
      navigate: (ctx: CommandContext) => `/servers/${ctx.serverId}/schedules`,
    },
    keywords: ["schedules", "automation", "cron"],
    priority: 37,
  },
  {
    id: "nav-server-network",
    label: "Network & Ports",
    description: "Manage network settings",
    icon: <Network className="size-4" />,
    category: "navigation",
    type: "simple",
    isAvailable: (ctx: CommandContext) => !!ctx.serverId,
    action: {
      navigate: (ctx: CommandContext) => `/servers/${ctx.serverId}/network`,
    },
    keywords: ["network", "ports", "allocations"],
    priority: 36,
  },
  {
    id: "nav-server-activity",
    label: "Activity Log",
    description: "View server activity",
    icon: <BookOpen className="size-4" />,
    category: "navigation",
    type: "simple",
    isAvailable: (ctx: CommandContext) => !!ctx.serverId,
    action: {
      navigate: (ctx: CommandContext) => `/servers/${ctx.serverId}/activity`,
    },
    keywords: ["activity", "logs", "history"],
    priority: 35,
  },
  {
    id: "nav-server-settings",
    label: "Server Settings",
    description: "Configure server settings",
    icon: <Settings className="size-4" />,
    category: "navigation",
    type: "simple",
    isAvailable: (ctx: CommandContext) => !!ctx.serverId,
    action: {
      navigate: (ctx: CommandContext) => `/servers/${ctx.serverId}/settings`,
    },
    keywords: ["settings", "configure"],
    priority: 34,
  },

  // Admin Navigation
  {
    id: "nav-admin-servers",
    label: "Manage Servers",
    description: "View all servers",
    icon: <Server className="size-4" />,
    category: "navigation",
    type: "simple",
    isAvailable: (ctx: CommandContext) => ctx.isAdmin,
    action: { navigate: "/admin/servers" },
    keywords: ["admin", "servers"],
    priority: 30,
  },
  {
    id: "nav-admin-nodes",
    label: "Manage Nodes",
    description: "View and manage nodes",
    icon: <Database className="size-4" />,
    category: "navigation",
    type: "simple",
    isAvailable: (ctx: CommandContext) => ctx.isAdmin,
    action: { navigate: "/admin/nodes" },
    keywords: ["admin", "nodes"],
    priority: 29,
  },
  {
    id: "nav-admin-users",
    label: "Manage Users",
    description: "View and manage users",
    icon: <Users className="size-4" />,
    category: "navigation",
    type: "simple",
    isAvailable: (ctx: CommandContext) => ctx.isAdmin,
    action: { navigate: "/admin/users" },
    keywords: ["admin", "users"],
    priority: 28,
  },
  {
    id: "nav-admin-analytics",
    label: "Analytics",
    description: "View analytics and statistics",
    icon: <BarChart3 className="size-4" />,
    category: "navigation",
    type: "simple",
    isAvailable: (ctx: CommandContext) => ctx.isAdmin,
    action: { navigate: "/admin/analytics" },
    keywords: ["admin", "analytics", "stats"],
    priority: 27,
  },
];
