// AUTO-GENERATED by scripts/codegen-errors.ts. Do not edit by hand.
// Run `pnpm --filter @workspace/shared codegen:errors` to regenerate.

export type ErrorCode =
  | "auth.login.email_unverified"
  | "auth.login.invalid_credentials"
  | "auth.session.expired"
  | "auth.session.invalid"
  | "auth.signup.disabled"
  | "auth.signup.email_taken"
  | "backups.locked"
  | "backups.not_found"
  | "backups.s3_credentials_missing"
  | "backups.upload_failed"
  | "blueprints.invalid_image"
  | "blueprints.not_found"
  | "blueprints.parse.invalid_json"
  | "blueprints.parse.schema_version_unsupported"
  | "blueprints.parse.unknown_field"
  | "files.decompress_failed"
  | "files.not_found"
  | "files.path_outside_jail"
  | "files.read_only"
  | "files.too_large"
  | "instances.nested_not_allowed"
  | "instances.pool_exhausted"
  | "internal.unexpected"
  | "nodes.has_servers"
  | "nodes.not_found"
  | "nodes.pair.token_already_claimed"
  | "nodes.pair.token_expired"
  | "nodes.pair.token_invalid"
  | "nodes.unreachable"
  | "permissions.denied"
  | "rate_limit.exceeded"
  | "schedules.cron_invalid"
  | "schedules.not_found"
  | "servers.action.already_running"
  | "servers.action.invalid_state"
  | "servers.action.suspended"
  | "servers.allocations.limit_reached"
  | "servers.cannot_remove_primary_allocation"
  | "servers.create.allocation_unavailable"
  | "servers.create.no_free_allocation"
  | "servers.create.node_at_capacity"
  | "servers.install.completed"
  | "servers.install.creating_container"
  | "servers.install.failed"
  | "servers.install.running_script"
  | "servers.lifecycle.crashed.console_match"
  | "servers.lifecycle.crashed.container_exit"
  | "servers.lifecycle.start_timeout"
  | "servers.not_found"
  | "servers.startup.invalid_docker_image"
  | "transfers.allocation_unavailable"
  | "transfers.not_found"
  | "transfers.push_failed"
  | "transfers.same_node"
  | "transfers.target_unreachable"
  | "transfers.token_invalid"
  | "users.not_found"
  | "validation.enum"
  | "validation.failed"
  | "validation.invalid"
  | "validation.invalid_type"
  | "validation.number.max"
  | "validation.number.min"
  | "validation.required"
  | "validation.string.email"
  | "validation.string.max"
  | "validation.string.min"
  | "validation.string.regex"
  | "validation.string.url"
  | "validation.string.uuid"

export const errorCodes = [
  "auth.login.email_unverified",
  "auth.login.invalid_credentials",
  "auth.session.expired",
  "auth.session.invalid",
  "auth.signup.disabled",
  "auth.signup.email_taken",
  "backups.locked",
  "backups.not_found",
  "backups.s3_credentials_missing",
  "backups.upload_failed",
  "blueprints.invalid_image",
  "blueprints.not_found",
  "blueprints.parse.invalid_json",
  "blueprints.parse.schema_version_unsupported",
  "blueprints.parse.unknown_field",
  "files.decompress_failed",
  "files.not_found",
  "files.path_outside_jail",
  "files.read_only",
  "files.too_large",
  "instances.nested_not_allowed",
  "instances.pool_exhausted",
  "internal.unexpected",
  "nodes.has_servers",
  "nodes.not_found",
  "nodes.pair.token_already_claimed",
  "nodes.pair.token_expired",
  "nodes.pair.token_invalid",
  "nodes.unreachable",
  "permissions.denied",
  "rate_limit.exceeded",
  "schedules.cron_invalid",
  "schedules.not_found",
  "servers.action.already_running",
  "servers.action.invalid_state",
  "servers.action.suspended",
  "servers.allocations.limit_reached",
  "servers.cannot_remove_primary_allocation",
  "servers.create.allocation_unavailable",
  "servers.create.no_free_allocation",
  "servers.create.node_at_capacity",
  "servers.install.completed",
  "servers.install.creating_container",
  "servers.install.failed",
  "servers.install.running_script",
  "servers.lifecycle.crashed.console_match",
  "servers.lifecycle.crashed.container_exit",
  "servers.lifecycle.start_timeout",
  "servers.not_found",
  "servers.startup.invalid_docker_image",
  "transfers.allocation_unavailable",
  "transfers.not_found",
  "transfers.push_failed",
  "transfers.same_node",
  "transfers.target_unreachable",
  "transfers.token_invalid",
  "users.not_found",
  "validation.enum",
  "validation.failed",
  "validation.invalid",
  "validation.invalid_type",
  "validation.number.max",
  "validation.number.min",
  "validation.required",
  "validation.string.email",
  "validation.string.max",
  "validation.string.min",
  "validation.string.regex",
  "validation.string.url",
  "validation.string.uuid",
] as const
