import {
  spawn,
  type ChildProcessByStdio,
} from "node:child_process"
import fs from "node:fs"
import path from "node:path"
import type { Readable } from "node:stream"

import { env } from "./env"

type DaemonChild = ChildProcessByStdio<null, Readable, Readable>

/**
 * Write the daemon's TOML config before spawning. Field names match the
 * struct the daemon parses (`apps/daemon/internal/config/config.go`).
 *
 * Node ID + signing key both come from `electron-store` so they're
 * stable across launches. The API's `/setup` route uses the same env
 * vars to insert the matching `nodes` row, so the two ends agree
 * without any explicit pairing handshake.
 */
const writeDaemonConfig = (params: {
  hmacKey: string
  nodeId: string
  apiBaseUrl: string
}): void => {
  // Quote with JSON.stringify — TOML strings allow the same escapes for
  // ASCII paths and arbitrary keys, so this is safe enough for our
  // hex/UUID/url values.
  const toml =
    `# Auto-generated by StellarStack Desktop. Source of truth for both\n` +
    `# values is stellar-secrets.json under the userData directory.\n\n` +
    `node_id = ${JSON.stringify(params.nodeId)}\n` +
    `signing_key = ${JSON.stringify(params.hmacKey)}\n` +
    `api_base_url = ${JSON.stringify(params.apiBaseUrl)}\n` +
    `http_listen = ${JSON.stringify(`127.0.0.1:${String(env.daemonPort)}`)}\n` +
    `sftp_listen = ${JSON.stringify(`127.0.0.1:${String(env.sftpPort)}`)}\n` +
    `data_dir = ${JSON.stringify(path.join(env.dataDir, "daemon-data"))}\n` +
    `history_lines = 150\n`
  fs.mkdirSync(path.dirname(env.daemonConfigPath), { recursive: true })
  fs.writeFileSync(env.daemonConfigPath, toml)
}

/**
 * Wraps the StellarStack daemon as a child process. The daemon owns the
 * Docker socket and exposes the per-server WebSocket on a local port.
 *
 * In a packaged build the binary lives at `resources/stellar-daemon`
 * (electron-builder copies it from the workspace). In dev we expect the
 * developer to have run `go build` inside `apps/daemon` and to have the
 * binary available — `pnpm dev` will warn loudly if it's missing.
 */
export class DaemonProcess {
  private child: DaemonChild | null = null

  public start(params: {
    hmacKey: string
    nodeId: string
    apiBaseUrl: string
  }): void {
    if (this.child !== null) return
    const binary = env.daemonBinaryPath
    if (!env.isDev && !fs.existsSync(binary)) {
      console.error(`[daemon] binary missing at ${binary}`)
      return
    }
    writeDaemonConfig(params)
    // The daemon's main has no `serve` subcommand — top-level invocation
    // with `-config` is the production entry point. `configure` is its
    // pairing helper which we deliberately don't call (we wrote the
    // config ourselves).
    const child = spawn(binary, ["-config", env.daemonConfigPath], {
      cwd: env.dataDir,
      stdio: ["ignore", "pipe", "pipe"] as const,
      env: { ...process.env, STELLAR_DESKTOP: "1" },
    }) as DaemonChild
    child.stdout.on("data", (chunk: Buffer) => {
      process.stdout.write(`[daemon] ${chunk.toString()}`)
    })
    child.stderr.on("data", (chunk: Buffer) => {
      process.stderr.write(`[daemon] ${chunk.toString()}`)
    })
    child.on("exit", (code) => {
      console.log(`[daemon] exited with code ${code ?? "?"}`)
      this.child = null
    })
    this.child = child
  }

  public async stop(): Promise<void> {
    const child = this.child
    if (child === null) return
    return new Promise<void>((resolve) => {
      const timer = setTimeout(() => {
        child.kill("SIGKILL")
      }, 5_000)
      child.once("exit", () => {
        clearTimeout(timer)
        resolve()
      })
      child.kill("SIGTERM")
    })
  }
}
