import { readFileSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

import { z } from "zod"

const here = dirname(fileURLToPath(import.meta.url))
const errorsJsonPath = resolve(here, "../locales/en/errors.json")
const validationJsonPath = resolve(here, "../locales/en/validation.json")
const outPath = resolve(here, "../src/error-codes.generated.ts")

const bundleSchema = z.record(z.string(), z.string())

const readKeys = (path: string): string[] => {
  const raw = readFileSync(path, "utf8")
  const parsed = bundleSchema.safeParse(JSON.parse(raw))
  if (!parsed.success) {
    throw new Error(`Invalid bundle at ${path}: ${parsed.error.message}`)
  }
  return Object.keys(parsed.data).sort()
}

const banner = [
  "// AUTO-GENERATED by scripts/codegen-errors.ts. Do not edit by hand.",
  "// Run `pnpm --filter @workspace/shared codegen:errors` to regenerate.",
  "",
].join("\n")

const renderUnion = (name: string, keys: string[]): string => {
  if (keys.length === 0) {
    return `export type ${name} = never`
  }
  const lines = keys.map((k) => `  | ${JSON.stringify(k)}`).join("\n")
  return `export type ${name} =\n${lines}`
}

const renderArray = (name: string, keys: string[]): string => {
  const lines = keys.map((k) => `  ${JSON.stringify(k)},`).join("\n")
  return `export const ${name} = [\n${lines}\n] as const`
}

const errors = readKeys(errorsJsonPath)
const validation = readKeys(validationJsonPath)
const all = [...new Set([...errors, ...validation])].sort()

const output = [
  banner,
  renderUnion("ErrorCode", all),
  "",
  renderArray("errorCodes", all),
  "",
].join("\n")

writeFileSync(outPath, output)
console.log(`Wrote ${outPath} (${all.length} codes)`)
